image: docker:latest
services:
  - docker:18.09.7-dind

stages:
  - build
  - lint
  - test

build:frontend:
  image: trion/ng-cli
  stage: build
  before_script:
    - cd 02.Frontend
    - npm ci
  script:
    - ng build --prod
  artifacts:
    expire_in: 1 day
    paths:
      - 02.Frontend/node_modules/
      - 02.Frontend/dist/
  tags:
    - docker

build:backend:
  image: node:lts-alpine
  allow_failure: true
  stage: build
  before_script:
    - cd 01.Backend
    - npm install
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - 01.Backend/node_modules/
      - 01.Backend/dist/
  tags:
    - docker

lint:frontend:
  image: trion/ng-cli
  allow_failure: true
  before_script:
    - cd 02.Frontend
  stage: lint
  script:
    - ng lint
  tags:
    - docker

lint:backend:
  image: node:lts-alpine
  allow_failure: true
  before_script:
    - cd 01.Backend
    - npm install
  stage: lint
  script:
    - npm run lint
  tags:
    - docker

test:frontend:karma:
  image: trion/ng-cli-karma
  stage: test
  allow_failure: false
  before_script:
    - cd 02.Frontend
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - 02.Frontend/coverage/
  tags:
    - docker

#test:frontend:e2e:
#  stage: test
#  image: trion/ng-cli-e2e
#  allow_failure: false
#  before_script:
#    - cd 01.Backend
#    - npm ci
#    - npm run start
#    - cd 02.Frontend
#    - npm ci
#  script:
#    - npm run e2e
#  tags:
#    - docker
