image: docker:latest
services:
  - docker:18.09.7-dind

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - 01.Backend/node_modules/
    - 01.Backend/dist/
    - 02.Frontend/node_modules/
    - 02.Frontend/dist/

stages:
  - install_packages
  - build
  - lint
  - test

install_packages:
  image: node
  stage: install_packages
  script:
    - cd 01.Backend
    - npm ci
    - cd 02.Frontend
    - npm ci
  tags:
    - docker

build:frontend:
  image: trion/ng-cli
  stage: build
  before_script:
    - cd 02.Frontend
  script:
    - ng build --prod
  tags:
    - docker

build:backend:
  image: nikolaik/python-nodejs:latest
  stage: build
  before_script:
    - cd 01.Backend
    - npm ci
  script:
    - npm run build
  tags:
    - docker

lint:frontend:
  image: trion/ng-cli
  allow_failure: true
  before_script:
    - cd 02.Frontend
  stage: lint
  script:
    - ng lint
  tags:
    - docker

lint:backend:
  image: nikolaik/python-nodejs:latest
  allow_failure: true
  before_script:
    - cd 01.Backend
  stage: lint
  script:
    - npm run lint
  tags:
    - docker

test:frontend:karma:
  image: trion/ng-cli-karma
  stage: test
  allow_failure: false
  before_script:
    - cd 02.Frontend
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - 02.Frontend/coverage/
  tags:
    - docker

#test:frontend:e2e:
#  stage: test
#  image: trion/ng-cli-e2e
#  allow_failure: false
#  before_script:
#    - cd 01.Backend
#    - npm ci
#    - npm run start
#    - cd 02.Frontend
#    - npm ci
#  script:
#    - npm run e2e
#  tags:
#    - docker
